@extends('layouts.admin')
@section('content')
<style>
.user-status-badge{font-size:.68rem;letter-spacing:.1em;text-transform:uppercase;padding:.55rem .75rem;background:#e8f1e9;color:#52765a}.user-status-badge.paused{background:#f5e8e3;color:#a06e63}.user-form-intro{display:flex;align-items:center;gap:1rem;border-bottom:1px solid #eee7e3;padding-bottom:1.2rem;margin-bottom:1.3rem}.user-avatar{width:52px;height:52px;border-radius:50%;display:grid;place-items:center;background:#3a2432;color:#e4bf8b;font:1.7rem var(--serif)}.user-form-intro h2,.security-card h2{font:600 1.9rem var(--serif);margin:0}.user-form-intro p:last-child,.security-card>p:not(.eyebrow){font-size:.75rem;color:#9a898e;margin:.25rem 0 0}.security-card{height:100%;background:#2b1a27;color:#f7e9df;border-color:#493344}.security-icon{display:grid;place-items:center;width:42px;height:42px;border:1px solid #a77b79;border-radius:50%;color:#d5aa7f;font-size:1.2rem;margin-bottom:2rem}.security-card .eyebrow{color:#d2a07e}.security-card h2 em{color:#d5aa7f}.security-row{display:flex;justify-content:space-between;gap:1rem;border-top:1px solid rgba(255,255,255,.12);padding:.8rem 0;margin-top:1.2rem;font-size:.7rem;color:#ae9ca4}.security-row strong{color:#f3dfcf;font-weight:500}.security-note{margin-top:1.4rem;padding:.8rem;background:rgba(255,255,255,.06);color:#b9a8af;font-size:.68rem;line-height:1.6}
</style>
<div class="studio-top"><div><p class="eyebrow">Private access</p><h1>Frontend <em>user</em></h1><p class="muted">Control who can unlock the birthday surprise from one simple place.</p></div><div class="user-status-badge {{ $guest?->status === 'active' ? 'active' : 'paused' }}">● {{ $guest?->status === 'active' ? 'Surprise is live' : 'Surprise is paused' }}</div></div>
@include('admin.partials.flash')
<div class="row g-4"><div class="col-xl-8"><form method="POST" action="{{ route('admin.user.update') }}" class="studio-card form-card"><div class="user-form-intro"><div class="user-avatar">{{ $guest ? mb_strtoupper(mb_substr($guest->name, 0, 1)) : '♡' }}</div><div><p class="eyebrow">Guest account</p><h2>{{ $guest?->name ?: 'Create the frontend account' }}</h2><p>This is the account used on the main login screen.</p></div></div>@csrf @method('PUT')<label>Display name</label><input name="name" value="{{ old('name',$guest?->name ?: 'My Love') }}" required><div class="row g-3"><div class="col-md-6"><label>Frontend username</label><input name="username" value="{{ old('username',$guest?->username) }}" placeholder="e.g. mylove" required></div><div class="col-md-6"><label>Frontend email</label><input type="email" name="email" value="{{ old('email',$guest?->email) }}" placeholder="name@example.com" required></div></div><label>New password <small>{{ $guest ? 'leave blank to keep current password' : 'required for first setup' }}</small></label><input type="password" name="password" placeholder="minimum 8 characters" {{ $guest ? '' : 'required' }}><label>Access status</label><select name="status"><option value="active" @selected(($guest?->status ?? 'active') === 'active')>Active — allow access</option><option value="paused" @selected($guest?->status === 'paused')>Paused — block access</option></select><button class="btn btn-dark-gold mt-4">Save frontend access</button></form></div><div class="col-xl-4"><div class="studio-card security-card"><span class="security-icon">♙</span><p class="eyebrow">How it works</p><h2>One account.<br><em>One surprise.</em></h2><p>These credentials unlock the private birthday experience at the main website URL.</p><div class="security-row"><span>Login ID</span><strong>{{ $guest?->username ?: 'Not set' }}</strong></div><div class="security-row"><span>Password</span><strong>••••••••</strong></div><div class="security-note">Passwords are securely hashed before they are saved. The current password is never shown here.</div></div></div></div>
@endsection
